### ISSUE TITLE
 what are the highest expressors of Elp5 in mouse?

### ISSUE THREAD

**Issue by iosonofabio** [fabilab/cell_atlas_approximations_HI#111]
fails to give an answer with no explanation

@YingX97

**Comment by YingX97** [comment]
Hi Fabio,

API server throws 500 instead of "invalid feature" when querying this. 

let api = require('@fabilab/atlasapprox')
let params={organism:'m_musculus', feature:'Elp5'}
await api.highest_measurement(params)
Uncaught { status: 500, message: 'Internal Server Error', error: undefined }

I want to run the API locally but it requires a secret_key.txt that I don't have. Could you send me a copy of it so that I can debug this?

Cheers, 
Ying

**Comment by iosonofabio** [comment]
Hi Ying,

Just use a random string in a text file to test locally 😅

Cheers, 
Fabio

**Comment by iosonofabio** [comment]
I fixed it, there was a bug in the order of 3 lines of code. It's activating the remote deployment in a few minutes

**Comment by YingX97** [comment]
Ok, thank you.
